name:  Frontend
on: 
  push:
    branches: ["main"]
    paths:
      - 'Frontend/**'

permissions:
  id-token: write
  contents: read
jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        # checkout the repo
        - uses: actions/checkout@v3
        - name: Azure login
          uses: azure/login@v2
          with:
              client-id: ${{ secrets.AZURE_CLIENT_ID }}
              tenant-id: ${{ secrets.AZURE_TENANT_ID }}
              subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        - name: Login to ACR
          run: az acr login --name ${{ secrets.REGISTRY_NAME }}
          
        - name: Build and push image to ACR
          run: |
            docker build ./Frontend -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/frontend:latest
            docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/frontend:latest
        - name: 'Deploy to Azure Container Instances'
          uses: 'azure/aci-deploy@v1'
          with:
            resource-group: ${{ secrets.RESOURCE_GROUP_NAME }}
            dns-name-label: backend-${{ github.run_number }}
            image: ${{ secrets.REGISTRY_LOGIN_SERVER }}/frontend:latest
            registry-login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
            registry-username: ${{ secrets.REGISTRY_USERNAME }}
            registry-password: ${{ secrets.REGISTRY_PASSWORD }}
            name: frontend
            location: 'east us'
